- name: Make .sync/dev directory
  file:
    path: "{{ target_home }}/.sync/dev"
    state: directory
    owner:  "{{ target_user }}"
    group:  "{{ target_group }}"
    mode: 0750

- name: Download Conda installer
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
    checksum: sha256:b820dde1a0ba868c4c948fe6ace7300a252b33b5befd078a15d4a017476b8979
    dest: "{{ target_home }}/.sync/dev/Miniconda2-latest-Linux-x86_64.sh"
    owner: "{{ target_user }}"
    group: "{{ target_group }}"
    mode: "0744"

- name: Install Conda
  become_user: "{{ target_user }}"
  shell: "{{ target_home }}/.sync/dev/Miniconda2-latest-Linux-x86_64.sh -f -b && touch {{ target_home }}/.sync/dev/conda2-installed"
  args:
    creates: "{{ target_home }}/.sync/dev/conda2-installed"

- name: Install Conda Bash
  become_user: "{{ target_user }}"
  shell: "{{ target_home }}/miniconda2/condabin/conda init bash && touch {{ target_home }}/.sync/dev/conda2-bash-setup"
  args:
    creates: "{{ target_home }}/.sync/dev/conda2-bash-setup"
