- name: Install mercurial
  become_user: "{{ target_user }}"
  shell: "/root/miniconda3/condabin/conda install --yes mercurial && touch {{ target_home }}/.sync/dev/mercurial-installed"
  args:
    creates: "{{ target_home }}/.sync/dev/mercurial-installed"
  when: ansible_facts['architecture'] == "x86_64"

- name: Install mercurial-git
  become_user: "{{ target_user }}"
  shell: "/root/miniconda3/condabin/conda install --yes -c conda-forge hg-git && touch {{ target_home }}/.sync/dev/hg-git-installed"
  args:
    creates: "{{ target_home }}/.sync/dev/hg-git-installed"
  when: ansible_facts['architecture'] == "x86_64"

- name: Install dulwich
  become_user: "{{ target_user }}"
  shell: "/root/miniconda3/condabin/conda install --yes dulwich && touch {{ target_home }}/.sync/dev/dulwich-installed"
  args:
    creates: "{{ target_home }}/.sync/dev/dulwich-installed"
  when: ansible_facts['architecture'] == "x86_64"

- name: where is hg-git
  shell: "/root/miniconda3/condabin/conda list | grep hg-git | awk '{print $1\"-\"$2\"-\"$3}'"
  register: hggitwhere

- set_fact: 
    hggitpath={{ hggitwhere.stdout }}

- name: .hgrc git 
  ini_file:
    create: true
    path: "{{ target_home }}/.hgrc"
    owner:  "{{ target_user }}"
    group:  "{{ target_group }}"
    mode: 0440
    backup: true
    section: extensions
    option: hggit
    value: "/root/miniconda3/pkgs/{{ hggitpath }}/site-packages/hggit"
 
- name: .hgrc bookmarks
  ini_file:
    path: "{{ target_home }}/.hgrc"
    backup: true
    section: extensions
    option: hgext.bookmarks
    value: ""
 
- name: .hgrc amend
  ini_file:
    path: "{{ target_home }}/.hgrc"
    backup: true
    section: extensions
    option: amend
    value: ""
 
- name: .hgrc automv
  ini_file:
    path: "{{ target_home }}/.hgrc"
    backup: true
    section: extensions
    option: automv
    value: ""
 
- name: .hgrc rebase
  ini_file:
    path: "{{ target_home }}/.hgrc"
    backup: true
    section: extensions
    option: rebase
    value: ""
 
- name: .hgrc split
  ini_file:
    path: "{{ target_home }}/.hgrc"
    backup: true
    section: extensions
    option: split
    value: ""
 
- name: .hgrc beautifygraph
  ini_file:
    path: "{{ target_home }}/.hgrc"
    backup: true
    section: extensions
    option: beautifygraph
    value: ""
 
- name: .hgrc verbose
  ini_file:
    path: "{{ target_home }}/.hgrc"
    backup: true
    section: ui
    option: verbose
    value: "true"
 
- name: .hgrc username
  ini_file:
    path: "{{ target_home }}/.hgrc"
    backup: true
    section: ui
    option: username
    value: "{{ lookup('ansible.builtin.env', 'GIT_NAME', default='nobody') }} <{{ lookup('ansible.builtin.env', 'GIT_EMAIL', default='nobody@nowhere.edu') }}>"
