- name: Add key for VS Code
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc

- name: Add repo for VS Code
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main

- name: Install vscode
  package:
    name: code
    state: present
